export const defaultGuildConfig = {
  guildId: "",
  prefix: ".",
  tag: "",
  secondaryTag: "",
  botOwners: [],
  itemPrices: {},
  disabledItems: [],
  roles: {
    man: [],
    woman: [],
    member: [],
    unregistered: [],
    suspicious: [],
    tagRole: [],
    booster: [],
    jail: [],
    chatMute: [],
    voiceMute: [],
    warnRoles: [],
    staffRoles: [],
    registerStaff: [],
    moderationStaff: [],
    vip: []
  },
  channels: {
    generalChat: "",
    registerChat: "",
    welcomeVoice: [],
    inviteLog: "",
    penaltyLog: "",
    registerLog: "",
    voiceLog: "",
    messageLog: "",
    guardLog: "",
    ticketCategory: "",
    customVoiceCategory: "",
    customVoiceChannel: "",
    mediaChannels: [],
    weeklyRewardLog: ""
  },
  autoResponders: [],
  weeklyRewards: [],
  limits: {
    pointLimit: 100,
    banLimit: 3,
    kickLimit: 3,
    jailLimit: 5,
    roleDeleteLimit: 1,
    roleCreateLimit: 2,
    channelDeleteLimit: 1,
    channelCreateLimit: 2
  },
  guard: {
    active: true,
    safeUsers: [],
    safeRoles: [],
    safeBots: [],
    blockWebhooks: true,
    blockBots: true
  },
  commands: {
    jail: { enabled: true, customName: "jail", minStaffRole: "" },
    unjail: { enabled: true, customName: "unjail", minStaffRole: "" },
    mute: { enabled: true, customName: "mute", minStaffRole: "" },
    unmute: { enabled: true, customName: "unmute", minStaffRole: "" },
    vmute: { enabled: true, customName: "vmute", minStaffRole: "" },
    unvmute: { enabled: true, customName: "unvmute", minStaffRole: "" },
    ban: { enabled: true, customName: "ban", minStaffRole: "" },
    unban: { enabled: true, customName: "unban", minStaffRole: "" },
    sicil: { enabled: true, customName: "sicil", minStaffRole: "" },
    cezapuan: { enabled: true, customName: "cezapuan", minStaffRole: "" },
    snipe: { enabled: true, customName: "snipe", minStaffRole: "" },
    kayit: { enabled: true, customName: "kayit", minStaffRole: "" },
    erkek: { enabled: true, customName: "erkek", minStaffRole: "" },
    kadin: { enabled: true, customName: "kadin", minStaffRole: "" },
    isim: { enabled: true, customName: "isim", minStaffRole: "" },
    isimler: { enabled: true, customName: "isimler", minStaffRole: "" },
    stat: { enabled: true, customName: "stat", minStaffRole: "" },
    topstat: { enabled: true, customName: "topstat", minStaffRole: "" },
    gorev: { enabled: true, customName: "gorev", minStaffRole: "" },
    coin: { enabled: true, customName: "coin", minStaffRole: "" },
    market: { enabled: true, customName: "market", minStaffRole: "" },
    blackjack: { enabled: true, customName: "blackjack", minStaffRole: "" },
    rulet: { enabled: true, customName: "rulet", minStaffRole: "" },
    slot: { enabled: true, customName: "slot", minStaffRole: "" },
    crash: { enabled: true, customName: "crash", minStaffRole: "" },
    borsa: { enabled: true, customName: "borsa", minStaffRole: "" },
    al: { enabled: true, customName: "al", minStaffRole: "" },
    sat: { enabled: true, customName: "sat", minStaffRole: "" },
    soygun: { enabled: true, customName: "soygun", minStaffRole: "" },
    kpi: { enabled: true, customName: "kpi", minStaffRole: "" },
    cekilis: { enabled: true, customName: "cekilis", minStaffRole: "" }
  },
  penaltyThresholds: {
    mute: 40,
    jail: 80,
    ban: 150
  },
  leveling: {
    enabled: true,
    messageXp: 15,
    voiceXpPerMinute: 20,
    roleRewards: []
  },
  guardPanic: {
    enabled: true,
    threshold: 5,
    timeWindowMs: 5000,
    isPanic: false
  },
  permissionAudit: {
    enabled: true,
    dangerousPermissions: ["Administrator", "ManageGuild", "ManageRoles", "ManageChannels", "BanMembers", "KickMembers"]
  },
  filters: {
    customWords: [],
    linkFilter: true,
    capsFilter: true,
    spamFilter: true
  },
  databaseProvider: {
    provider: "POSTGRESQL",
    connectionUri: ""
  },
  economyMarket: {
    goldPrice: 2500,
    btcPrice: 65000,
    lastUpdate: new Date()
  },
  messages: {
    jailPunish: { format: "COMPONENTS_V2", content: "### 🛡️ Karantina Protokolü Uygulandı\n▫️ **Kullanıcı:** {user}\n▫️ **Yetkili:** {staff}\n▫️ **Ceza Puanı:** `+{points}`\n▫️ **Gerekçe:** `{reason}`\n-# 🔒 Güvenlik Karantinası • Tüm erişim izinleri askıya alındı" },
    jailLift: { format: "COMPONENTS_V2", content: "### 🟢 Karantina Cezası Kaldırıldı\n▫️ **Kullanıcı:** {user}\n▫️ **Yetkili:** {staff}\n-# ✨ Erişim İadesi • Standart üye izinleri tanımlandı" },
    mutePunish: { format: "COMPONENTS_V2", content: "### 🔇 Metin Susturma (Mute) Uygulandı\n▫️ **Kullanıcı:** {user}\n▫️ **Yetkili:** {staff}\n▫️ **Gerekçe:** `{reason}`\n-# ⏳ Metin Kısıtlaması • Kanallara mesaj gönderme engellendi" },
    muteLift: { format: "COMPONENTS_V2", content: "### 🔊 Metin Susturması Kaldırıldı\n▫️ **Kullanıcı:** {user}\n▫️ **Yetkili:** {staff}\n-# ✨ İletişim İzni • Metin kanalları erişime açıldı" },
    vmutePunish: { format: "COMPONENTS_V2", content: "### 🎙️ Ses Susturma (VMute) Uygulandı\n▫️ **Kullanıcı:** {user}\n▫️ **Yetkili:** {staff}\n▫️ **Gerekçe:** `{reason}`\n-# 🔇 Ses Kısıtlaması • Ses kanallarında konuşma kapatıldı" },
    vmuteLift: { format: "COMPONENTS_V2", content: "### 🎙️ Ses Susturması Kaldırıldı\n▫️ **Kullanıcı:** {user}\n▫️ **Yetkili:** {staff}\n-# 🔊 Ses İletişimi • Ses kanalları serbestçe kullanılabilir" },
    banPunish: { format: "COMPONENTS_V2", content: "### ⛔ Sunucudan Uzaklaştırıldı (Ban)\n▫️ **Yasaklanan:** {user}\n▫️ **Yetkili:** {staff}\n▫️ **Gerekçe:** `{reason}`\n-# 🚫 Kalıcı Yasaklama • Giriş protokolü bloke edildi" },
    banLift: { format: "COMPONENTS_V2", content: "### 🟢 Sunucu Yasağı Kaldırıldı\n▫️ **Kullanıcı:** {user}\n▫️ **Yetkili:** {staff}\n-# ✨ Yasak Kaldırma • Sunucuya katılım engeli sonlandırıldı" },
    warnAdd: { format: "COMPONENTS_V2", content: "### ⚠️ Resmi Ceza Uyarısı Verildi\n▫️ **Uyarılan:** {user}\n▫️ **Yetkili:** {staff}\n▫️ **Gerekçe:** `{reason}`\n-# 📋 Sicil Kaydı • Tekrarında otomatik yaptırım uygulanır" },
    warnClean: { format: "COMPONENTS_V2", content: "### 🧹 Uyarı Sicili Temizlendi\n▫️ **Kullanıcı:** {user}\n▫️ **Yetkili:** {staff}\n-# ✨ Temiz Sicil • Aktif uyarı puanları sıfırlandı" },
    lockChannel: { format: "COMPONENTS_V2", content: "### 🔒 Kanal Erişime Kapatıldı\n▫️ **Yetkili:** {staff}\n▫️ **Kilit Süresi:** `{duration}`\n-# ⛔ Kanal Kilidi • Üyelerin mesaj gönderimi durduruldu" },
    unlockChannel: { format: "COMPONENTS_V2", content: "### 🔓 Kanal Erişime Açıldı\n▫️ Kanal erişimi normale döndü. Sohbet kurallarına uymaya özen gösterin.\n-# 💬 Genel Sohbet • Kanal kilidi kaldırıldı" },
    sicilClean: { format: "COMPONENTS_V2", content: "### 📋 Sicil ve Ceza Kaydı Temiz\n▫️ **Kullanıcı:** {user}\n▫️ **Toplam Ceza Puanı:** `0`\n-# ✨ Mükemmel Sicil • Kayıtlarda herhangi bir ihlal bulunmuyor" },
    sicilRecord: { format: "COMPONENTS_V2", content: "### 📋 Sicil ve Ceza Dosyası\n▫️ **Kullanıcı:** {user}\n▫️ **Toplam Ceza Puanı:** `{points}`\n\n{records}\n-# 📊 Ceza Arşivi • Veritabanı kayıtları listelendi" },
    penaltyPoints: { format: "COMPONENTS_V2", content: "### 📊 Aktif Ceza Puanı Durumu\n▫️ **Kullanıcı:** {user}\n▫️ **Mevcut Puan:** `{points}` / `{limit}`\n-# ⚠️ Sınır Takibi • Limit aşıldığında kademeli ceza devreye girer" },
    snipeEmpty: { format: "COMPONENTS_V2", content: "### 🗑️ Silinen Mesaj Kaydı Yok\n▫️ Bu kanalda yakın zamanda silinmiş bir mesaj bulunmuyor.\n-# 🕒 Veri Hafızası • Yalnızca son silinen mesajlar tutulur" },
    snipeMessage: { format: "COMPONENTS_V2", content: "### 🔍 Yakalanan Silinmiş Mesaj\n▫️ **Yazar:** <@{authorId}>\n▫️ **Zaman:** `{time}`\n```text\n{content}\n```\n-# 🕵️ Snipe Takipçisi • Son silinen içerik" },
    registerWelcome: { format: "COMPONENTS_V2", content: "### ✦ Hoş Geldin!\n▫️ Selam {user}, sunucumuza hoş geldin! Kayıt olmak için ses teyit odalarına katılabilirsin.\n-# 📜 Kurallar • Sunucu kurallarını okumayı unutmayınız" },
    registerSuccess: { format: "COMPONENTS_V2", content: "### 👥 Kayıt İşlemi Tamamlandı\n▫️ **Kaydedilen:** {user}\n▫️ **Yetkili:** {staff}\n▫️ **Verilen Rol / Cinsiyet:** `{gender}`\n-# 🛡️ Üye Kabulü • Sunucu yetkileri ve rolleri teslim edildi" },
    suspiciousAlert: { format: "COMPONENTS_V2", content: "### 🛡️ Şüpheli Hesap Karantinası\n▫️ **Kullanıcı:** {user}\n▫️ **Tespit Nedeni:** `Yeni Açılmış Hesap (< 7 Gün)`\n-# ⚠️ Güvenlik Filtresi • Şüpheli hesap izole edildi" },
    serverStats: { format: "COMPONENTS_V2", content: "### 📈 Sunucu İstatistik Paneli\n▫️ 👥 **Toplam Üye:** `{total}`\n▫️ 🏷️ **Taglı Üye:** `{tagged}`\n▫️ 🎙️ **Sesteki Üyeler:** `{voice}`\n▫️ 🚀 **Takviye (Boost):** `{boosts}`\n-# 🌐 Gerçek Zamanlı • Sunucu genel aktivite durumu" },
    nameChanged: { format: "COMPONENTS_V2", content: "### 📝 İsim Değişikliği Onaylandı\n▫️ **Kullanıcı:** {user}\n▫️ **Yeni İsim:** `{name}`\n-# 📜 Kimlik Kaydı • Değişiklik isim geçmişine işlendi" },
    nameHistory: { format: "COMPONENTS_V2", content: "### 📜 İsim Değişiklik Geçmişi\n▫️ **Kullanıcı:** {user} • **Toplam:** `{count}`\n\n{records}\n-# 🗂️ Arşiv • Geçmiş kimlik ve kayıt logları" },
    coinBalance: { format: "COMPONENTS_V2", content: "### 💳 Bakiye ve Finansal Durum\n▫️ **Hesap Sahibi:** {user}\n▫️ 👛 **Cüzdan:** `{wallet}` Coin\n▫️ 🏦 **Banka:** `{bank}` Coin\n-# 💎 Finans Güvencesi • Public Bot Finans Altyapısı" },
    dailyReward: { format: "COMPONENTS_V2", content: "### 🎁 Günlük Maaş / Ödül Alındı\n▫️ **Hesap Sahibi:** {user}\n▫️ 💰 **Kazanılan:** `+{amount}` Coin\n-# ⏳ Sonraki Ödül • 24 saat sonra tekrar alabilirsiniz" },
    coinTransferSuccess: { format: "COMPONENTS_V2", content: "### 💸 Para Transferi Onaylandı\n▫️ **Gönderen:** {user}\n▫️ **Alıcı:** {target}\n▫️ **Transfer Tutarı:** `{amount}` Coin\n-# ⚡ Anlık Transfer • Hesap bakiyeleri güncellendi" },
    blackjackTable: { format: "COMPONENTS_V2", content: "### 🃏 21 (Blackjack) Masası\n▫️ 💰 **Bahis:** `{bet}` Coin\n▫️ 👤 **Eliniz:** `[ {cards} ]` (Toplam: **{total}**)\n▫️ 🤖 **Krupiye:** `[ {dealer} - ? ]`\n-# 🎮 Oyun Sırası • Aşağıdaki butonlarla hamlenizi belirleyin" },
    blackjackWin: { format: "COMPONENTS_V2", content: "### 🎉 Blackjack - Zafer!\n▫️ 🏆 **Kazanılan:** `+{amount}` Coin\n▫️ 💳 **Güncel Bakiye:** `{balance}` Coin\n-# 🥇 Kazandınız • Krupiyeyi yenerek bahsinizi katladınız" },
    blackjackLose: { format: "COMPONENTS_V2", content: "### 💀 Blackjack - Kaybettiniz\n▫️ 📉 **Kaybedilen:** `-{amount}` Coin\n▫️ 💳 **Güncel Bakiye:** `{balance}` Coin\n-# 🎲 Şans • Krupiye bu eli önde bitirdi" },
    blackjackPush: { format: "COMPONENTS_V2", content: "### ⚖️ Blackjack - Berabere (Push)\n▫️ ↩️ **İade Edilen:** `{amount}` Coin\n▫️ 💳 **Güncel Bakiye:** `{balance}` Coin\n-# 🤝 Eşit Skor • Bahis cüzdanınıza iade edildi" },
    slotWin: { format: "COMPONENTS_V2", content: "### 🎰 Slot Makinesi - Jackpot!\n▫️ 🎰 **Çarklar:** `[ {reel1} | {reel2} | {reel3} ]`\n▫️ 🌟 **Çarpan:** `{multiplier}x` • **Kazanılan:** `+{amount}` Coin\n▫️ 💳 **Güncel Cüzdan:** `{balance}` Coin\n-# 💎 Şanslı Döndürme • Çark kombinasyonu tuttu" },
    slotLose: { format: "COMPONENTS_V2", content: "### 🎰 Slot Makinesi - Kazanamadınız\n▫️ 🎰 **Çarklar:** `[ {reel1} | {reel2} | {reel3} ]`\n▫️ 📉 **Kaybedilen:** `-{amount}` Coin\n▫️ 💳 **Güncel Cüzdan:** `{balance}` Coin\n-# 🎲 Tekrar Deneyin • Şansınızı bir sonraki çevirmede deneyin" },
    ruletWin: { format: "COMPONENTS_V2", content: "### 🎡 Rulet - Kazandınız!\n▫️ 🎯 **Gelen Sonuç:** `{color}` (`{number}`)\n▫️ 💰 **Kazanılan:** `+{amount}` Coin\n▫️ 💳 **Güncel Bakiye:** `{balance}` Coin\n-# 🍀 Çark Döndü • İsabetli tahminle kazandınız" },
    ruletLose: { format: "COMPONENTS_V2", content: "### 🎡 Rulet - Kaybettiniz\n▫️ 🎯 **Gelen Sonuç:** `{color}` (`{number}`)\n▫️ 📉 **Kaybedilen:** `-{amount}` Coin\n▫️ 💳 **Güncel Bakiye:** `{balance}` Coin\n-# 🎲 Şans • Top beklenen bölgeye düşmedi" },
    depositSuccess: { format: "COMPONENTS_V2", content: "### 🏦 Vadeli Mevduat Hesabı Açıldı\n▫️ 💰 **Yatırılan Tutar:** `{amount}` Coin\n▫️ 📈 **Vade Getirisi:** `%5 Faiz / 24 Saat`\n-# 🔒 Güvenli Fon • Vade dolduğunda ana para ve faiz aktarılır" },
    companyCreated: { format: "COMPONENTS_V2", content: "### 🏢 Kurumsal Şirket Kuruluşu Onaylandı\n▫️ 🏷️ **Şirket Adı:** `{name}`\n-# 💼 Şirketler Masası • Vergi ve ticaret tescili yapıldı" },
    propertyBought: { format: "COMPONENTS_V2", content: "### 🏠 Gayrimenkul Yatırımı Yapıldı\n▫️ 🔑 **Satın Alınan Mülk:** `{type}`\n-# 🏘️ Tapu Kaydı • Günlük kira geliri portföye bağlandı" },
    lotteryWin: { format: "COMPONENTS_V2", content: "### 🎟️ Piyango Büyük İkramiye!\n▫️ 🌟 **Kazanılan:** `+{amount}` Coin\n-# 🎊 Şanslı Talihli • Bilet numaranız çekilişte kazandı" },
    mineSuccess: { format: "COMPONENTS_V2", content: "### ⛏️ Maden Kazısı Başarılı\n▫️ 💎 **Cevher:** `{mineral}`\n▫️ 💰 **Kazanılan Değer:** `+{amount}` Coin\n-# 🗺️ Kazı Başarılı • Maden cevheri paraya dönüştürüldü" },
    fishSuccess: { format: "COMPONENTS_V2", content: "### 🎣 Balık Avı Başarılı\n▫️ 🐟 **Yakalanan:** `{fish}`\n▫️ 💰 **Satış Değeri:** `+{amount}` Coin\n-# 🌊 Deniz Avı • Balık pazarında satış gerçekleştirildi" },
    customRoomCreated: { format: "COMPONENTS_V2", content: "### 🔊 Özel Ses Odası Oluşturuldu\n▫️ 👤 **Oda Sahibi:** {user}\n▫️ 🚪 **Kanalınız:** {channel}\n-# 🎛️ Yönetim Paneli • Aşağıdaki butonlarla odanızı yönetebilirsiniz" },
    roomLocked: { format: "COMPONENTS_V2", content: "### 🔒 Özel Oda Kilitlendi\n▫️ Özel ses odanız kilitlendi. Yabancı üyeler odaya katılamaz.\n-# ⛔ Güvenlik • Giriş izinleri devre dışı" },
    roomUnlocked: { format: "COMPONENTS_V2", content: "### 🔓 Özel Oda Kilidi Açıldı\n▫️ Özel ses odanızın kilidi açıldı. Artık tüm üyeler odaya katılabilir.\n-# 🌐 Genel Erişim • Oda herkese açık" },
    ticketCreated: { format: "COMPONENTS_V2", content: "### 🎫 Destek Talebi Açıldı\n▫️ 👤 **Talep Sahibi:** {user}\n▫️ 📩 **Destek Kanalı:** {channel}\n-# ⚡ Yetkili Ekip • Talebiniz sıraya alındı ve inceleniyor" },
    ticketClosed: { format: "COMPONENTS_V2", content: "### 🔒 Destek Talebi Sonlandırıldı\n▫️ Destek talebi yetkili tarafından sonlandırıldı. Kanal 5 saniye içinde silinecektir...\n-# 🗃️ Arşiv • Talep geçmişi kayıt altına alındı" },
    afkSet: { format: "COMPONENTS_V2", content: "### 💤 AFK Moduna Geçildi\n▫️ **Kullanıcı:** {user}\n▫️ **Durum / Sebep:** `{reason}`\n-# 💬 Otomatik Bildirim • Kanala mesaj yazdığınızda AFK modu kaldırılır" },
    suggestionNew: { format: "COMPONENTS_V2", content: "### 💡 Yeni Sunucu Önerisi\n▫️ **Öneren:** {user}\n```text\n{content}\n```\n-# 🗳️ Topluluk Oylaması • Tercihinizi butonlarla belirtin" },
    confessionNew: { format: "COMPONENTS_V2", content: "### 🎭 Anonim İtiraf Kutusu\n```text\n{content}\n```\n-# 🕵️ Tamamen Gizli • Kimlik bilgileri gizlenmiştir" },
    birthdayWish: { format: "COMPONENTS_V2", content: "### 🎂 Doğum Günün Kutlu Olsun!\n▫️ Sevgili {user}, yeni yaşın sağlık, mutluluk ve başarı getirsin! Nice mutlu senelere! 🎉\n-# 🎈 Kutlama • Mutlu Yıllar!" },
    radioStart: { format: "COMPONENTS_V2", content: "### 📻 Canlı Radyo Yayını Başlatıldı\n▫️ 🎵 **İstasyon:** `{station}`\n▫️ 🔗 **Yayın Akışı:** `{url}`\n-# 🎧 7/24 Kesintisiz • Keyifli dinlemeler" },
    userStats: { format: "COMPONENTS_V2", content: "### 📊 Kullanıcı Aktivite İstatistikleri\n▫️ **Kullanıcı:** {user}\n▫️ 🎙️ **Ses Aktifliği (Toplam / Hafta / Gün):** `{totalVoice}` • `{weeklyVoice}` • `{dailyVoice}`\n▫️ 💬 **Mesaj Aktifliği (Toplam / Hafta / Gün):** `{totalMsgs}` • `{weeklyMsgs}` • `{dailyMsgs}`\n-# 📈 İstatistik Motoru • Aktiflik verileri sunucu tabanlıdır" },
    topStats: { format: "COMPONENTS_V2", content: "### 🏆 {guild} En Aktifler Liderlik Tablosu\n{ranking}\n-# 🏅 Zirve Takibi • Sıralama haftalık ve genel aktivite verilerine göre hesaplanır" },
    staffTask: { format: "COMPONENTS_V2", content: "### 📋 Yetkili Haftalık Görev Durumu\n▫️ **Yetkili:** {user}\n▫️ 🎙️ **Ses Süresi:** `{voiceHours}` Saat\n▫️ 💬 **Mesaj Sayısı:** `{msgs}` Mesaj\n▫️ 👥 **Kayıt Sayısı:** `{regs}` Kayıt\n▫️ ⭐ **Toplam Puan:** `{points}` Puan\n-# 🎯 Haftalık Kota • Performans verileri günceldir" },
    attendanceReport: { format: "COMPONENTS_V2", content: "### 📢 Toplantı Yoklama Raporu\n▫️ 🔊 **Kanal:** {channel}\n▫️ 🟢 **Katılan:** `{attendedCount}` • 🔴 **Katılmayan:** `{missingCount}`\n▫️ 👥 **Katılanlar:** {attendedList}\n-# 📑 Yetkili Yoklaması • Katılım veritabanına mühürlendi" },
    guardAlert: { format: "COMPONENTS_V2", content: "### 🛡️ Güvenlik Bildirimi (Guard)\n▫️ 🚨 **Kullanıcı:** {user}\n▫️ ⚠️ **İhlal Nedeni:** `{reason}`\n-# 🛑 Acil Müdahale • Guard koruma kalkanı devreye girdi ve işlem geri alındı" }
  }
};
