export const defaultGuildConfig = {
  guildId: "",
  prefix: ".",
  tag: "",
  secondaryTag: "",
  roles: {
    man: [],
    woman: [],
    member: [],
    unregistered: [],
    suspicious: [],
    tagRole: "",
    booster: "",
    jail: "",
    chatMute: "",
    voiceMute: "",
    warnRoles: [],
    staffRoles: [],
    registerStaff: [],
    moderationStaff: [],
    vip: ""
  },
  channels: {
    generalChat: "",
    registerChat: "",
    welcomeVoice: [],
    inviteLog: "",
    penaltyLog: "",
    registerLog: "",
    voiceLog: "",
    messageLog: "",
    guardLog: "",
    ticketCategory: "",
    customVoiceCategory: "",
    customVoiceChannel: "",
    mediaChannels: [],
    weeklyRewardLog: ""
  },
  autoResponders: [],
  weeklyRewards: [],
  limits: {
    pointLimit: 100,
    banLimit: 3,
    kickLimit: 3,
    jailLimit: 5,
    roleDeleteLimit: 1,
    roleCreateLimit: 2,
    channelDeleteLimit: 1,
    channelCreateLimit: 2
  },
  guard: {
    active: true,
    safeUsers: [],
    safeRoles: [],
    safeBots: [],
    blockWebhooks: true,
    blockBots: true
  },
  commands: {
    jail: { enabled: true, customName: "jail", minStaffRole: "" },
    unjail: { enabled: true, customName: "unjail", minStaffRole: "" },
    mute: { enabled: true, customName: "mute", minStaffRole: "" },
    unmute: { enabled: true, customName: "unmute", minStaffRole: "" },
    vmute: { enabled: true, customName: "vmute", minStaffRole: "" },
    unvmute: { enabled: true, customName: "unvmute", minStaffRole: "" },
    ban: { enabled: true, customName: "ban", minStaffRole: "" },
    unban: { enabled: true, customName: "unban", minStaffRole: "" },
    sicil: { enabled: true, customName: "sicil", minStaffRole: "" },
    cezapuan: { enabled: true, customName: "cezapuan", minStaffRole: "" },
    snipe: { enabled: true, customName: "snipe", minStaffRole: "" },
    kayit: { enabled: true, customName: "kayit", minStaffRole: "" },
    erkek: { enabled: true, customName: "erkek", minStaffRole: "" },
    kadin: { enabled: true, customName: "kadin", minStaffRole: "" },
    isim: { enabled: true, customName: "isim", minStaffRole: "" },
    isimler: { enabled: true, customName: "isimler", minStaffRole: "" },
    stat: { enabled: true, customName: "stat", minStaffRole: "" },
    topstat: { enabled: true, customName: "topstat", minStaffRole: "" },
    gorev: { enabled: true, customName: "gorev", minStaffRole: "" },
    coin: { enabled: true, customName: "coin", minStaffRole: "" },
    market: { enabled: true, customName: "market", minStaffRole: "" },
    blackjack: { enabled: true, customName: "blackjack", minStaffRole: "" },
    rulet: { enabled: true, customName: "rulet", minStaffRole: "" },
    slot: { enabled: true, customName: "slot", minStaffRole: "" },
    crash: { enabled: true, customName: "crash", minStaffRole: "" },
    borsa: { enabled: true, customName: "borsa", minStaffRole: "" },
    al: { enabled: true, customName: "al", minStaffRole: "" },
    sat: { enabled: true, customName: "sat", minStaffRole: "" },
    soygun: { enabled: true, customName: "soygun", minStaffRole: "" },
    kpi: { enabled: true, customName: "kpi", minStaffRole: "" },
    cekilis: { enabled: true, customName: "cekilis", minStaffRole: "" }
  },
  penaltyThresholds: {
    mute: 40,
    jail: 80,
    ban: 150
  },
  leveling: {
    enabled: true,
    messageXp: 15,
    voiceXpPerMinute: 20,
    roleRewards: []
  },
  guardPanic: {
    enabled: true,
    threshold: 5,
    timeWindowMs: 5000,
    isPanic: false
  },
  permissionAudit: {
    enabled: true,
    dangerousPermissions: ["Administrator", "ManageGuild", "ManageRoles", "ManageChannels", "BanMembers", "KickMembers"]
  },
  filters: {
    customWords: [],
    linkFilter: true,
    capsFilter: true,
    spamFilter: true
  },
  economyMarket: {
    goldPrice: 2500,
    btcPrice: 65000,
    lastUpdate: new Date()
  },
  messages: {
    jailPunish: { format: "EMBED", content: "{user} kullanıcısı {staff} tarafından karantinaya (jail) gönderildi. Sebep: {reason} | Ceza Puanı: +{points}" },
    jailLift: { format: "EMBED", content: "{user} kullanıcısının karantina cezası {staff} tarafından kaldırıldı." },
    mutePunish: { format: "EMBED", content: "{user} kullanıcısı {staff} tarafından metin kanallarında susturuldu. Sebep: {reason}" },
    muteLift: { format: "EMBED", content: "{user} kullanıcısının metin susturması {staff} tarafından kaldırıldı." },
    vmutePunish: { format: "EMBED", content: "{user} kullanıcısı {staff} tarafından ses kanallarında susturuldu. Sebep: {reason}" },
    vmuteLift: { format: "EMBED", content: "{user} kullanıcısının ses susturması {staff} tarafından kaldırıldı." },
    banPunish: { format: "EMBED", content: "{user} kullanıcısı {staff} tarafından sunucudan yasaklandı. Sebep: {reason}" },
    banLift: { format: "EMBED", content: "{user} kullanıcısının sunucu yasağı {staff} tarafından kaldırıldı." },
    sicilClean: { format: "EMBED", content: "{user} adına kayıtlı herhangi bir ceza bulunmuyor. Toplam Ceza Puanı: 0" },
    sicilRecord: { format: "EMBED", content: "{user} kullanıcısının sicil kaydı:\nToplam Ceza Puanı: {points}\n\n{records}" },
    penaltyPoints: { format: "EMBED", content: "{user} adlı kullanıcının aktif ceza puanı: {points} / {limit}" },
    snipeEmpty: { format: "EMBED", content: "Bu kanalda son silinen herhangi bir mesaj bulunmuyor." },
    snipeMessage: { format: "EMBED", content: "Yazar: <@{authorId}>\nİçerik: {content}\nZaman: {time}" },
    registerWelcome: { format: "EMBED", content: "Aramıza hoş geldin {user}! Kayıt olmak için ses teyit odalarına bağlanabilirsiniz." },
    registerSuccess: { format: "EMBED", content: "{user} kullanıcısı {staff} tarafından {gender} olarak başarıyla kayıt edildi." },
    suspiciousAlert: { format: "EMBED", content: "{user} hesabınız 7 günden yeni olduğu için güvenlik nedeniyle şüpheli karantinasına alındı." },
    serverStats: { format: "EMBED", content: "Toplam Üye: {total}\nTaglı Üye: {tagged}\nSesteki Üye: {voice}\nTakviye Sayısı: {boosts}" },
    nameChanged: { format: "EMBED", content: "{user} kullanıcısının ismi {name} olarak güncellendi ve sicile işlendi." },
    nameHistory: { format: "EMBED", content: "{user} kullanıcısının geçmiş isimleri (Toplam {count}):\n\n{records}" },
    coinBalance: { format: "EMBED", content: "{user} Bakiye Durumu:\nCüzdan: {wallet} Coin\nBanka: {bank} Coin" },
    dailyReward: { format: "EMBED", content: "{user} günlük ödülünüz olan {amount} Coin hesabınıza aktarıldı!" },
    coinTransferSuccess: { format: "EMBED", content: "{user} başarıyla {target} kullanıcısına {amount} Coin gönderdi." },
    blackjackTable: { format: "EMBED", content: "Bahis: {bet} Coin\nSizin Kartlarınız: [ {cards} ] (Toplam: {total})\nKrupiye: [ {dealer} - ? ]" },
    blackjackWin: { format: "EMBED", content: "Tebrikler! Krupiyeyi yenerek {amount} Coin kazandınız. Yeni Bakiye: {balance}" },
    blackjackLose: { format: "EMBED", content: "Krupiye kazandı. {amount} Coin kaybettiniz. Yeni Bakiye: {balance}" },
    blackjackPush: { format: "EMBED", content: "Berabere! Bahis miktarınız olan {amount} Coin iade edildi. Yeni Bakiye: {balance}" },
    slotWin: { format: "EMBED", content: "[ {reel1} | {reel2} | {reel3} ]\nTebrikler! {multiplier}x katlayarak {amount} Coin kazandınız. Yeni Bakiye: {balance}" },
    slotLose: { format: "EMBED", content: "[ {reel1} | {reel2} | {reel3} ]\nBu turda kazanamadınız. {amount} Coin kaybettiniz. Yeni Bakiye: {balance}" },
    ruletWin: { format: "EMBED", content: "Top {color} ({number}) üzerine düştü!\nTebrikler! {amount} Coin kazandınız. Yeni Bakiye: {balance}" },
    ruletLose: { format: "EMBED", content: "Top {color} ({number}) üzerine düştü!\nKaybettiniz: {amount} Coin. Yeni Bakiye: {balance}" },
    customRoomCreated: { format: "EMBED", content: "{user} özel ses odanız oluşturuldu: {channel}" },
    roomLocked: { format: "EMBED", content: "Oda başarıyla kilitlendi. Yabancı üyeler artık odaya katılamaz." },
    roomUnlocked: { format: "EMBED", content: "Oda kilidi açıldı. Artık tüm üyeler katılabilir." },
    ticketCreated: { format: "EMBED", content: "{user} destek talebiniz açıldı: {channel}" },
    ticketClosed: { format: "EMBED", content: "Destek talebi sonlandırıldı. Kanal 5 saniye içinde silinecektir..." },
    userStats: { format: "EMBED", content: "{user} Aktivite İstatistikleri:\nSes Aktifliği (Toplam / Hafta / Gün): {totalVoice} / {weeklyVoice} / {dailyVoice}\nMesaj Aktifliği (Toplam / Hafta / Gün): {totalMsgs} / {weeklyMsgs} / {dailyMsgs}" },
    topStats: { format: "EMBED", content: "{guild} En Aktifler Sıralaması:\n\n{ranking}" },
    staffTask: { format: "EMBED", content: "{user} Haftalık Görev Durumu:\nSes: {voiceHours} Saat\nMesaj: {msgs} Mesaj\nKayıt: {regs} Kayıt\nToplam Puan: {points}" },
    attendanceReport: { format: "EMBED", content: "Toplantı Raporu - Kanal: {channel}\nKatılan Yetkili: {attendedCount} | Katılmayan: {missingCount}\nKatılanlar: {attendedList}" },
    guardAlert: { format: "EMBED", content: "Güvenlik Bildirimi: {user} yetkisiz işlem gerçekleştirdi: {reason}" }
  }
};
